swagger: "2.0"

info:
  title: Keras Model Server
  version: "1.0"

paths:
  /point/classify:
    post:
      summary: Get the poits og the pole and the intersec of the cables
      description: Generates a greeting message from a post, such as curl -F file=@sample.png http://localhost:8585/point/classify
      operationId: point.post_image
      consumes:
        - multipart/form-data
      produces:
        - text/json;
      responses:
        200:
          description: (x,y) poits of the top, botton, and all the intersecs
          schema:
            type: string
          examples:
            "text/json": "{top:[x,y],botton:[x,y],intersecs_i:[x,y]}"
      parameters:
        - name: file
          in: formData
          description: Image file to extract coordinates.
          required: true
          type: file

definitions:
  default-CORS-response:
      default:
        headers:
          Access-Control-Allow-Origin:
            type: string
